<?php

declare(strict_types=1);

use HalalPulse\Multibagger\MultibaggerScoringEngine;
use HalalPulse\Multibagger\ResearchEvidenceUrl;
use HalalPulse\Sharia\DecimalMath;
use HalalPulse\Web\Page;
use HalalPulse\Web\Request;
use HalalPulse\Web\Response;
use HalalPulse\Web\WebApplication;

$config=require dirname(__DIR__).'/app/bootstrap.php';$app=WebApplication::boot($config);$user=$app->session->currentUser($app->users);if($user===null)Response::redirect('/login.php',302);
$companyId=Request::isPost()?(int)Request::postString('company_id'):Request::queryInt('id',0);$company=$companyId>0?$app->multibagger->company($companyId):null;if($company===null){http_response_code(404);exit('Company not found.');}
$validDate=static function(string $value):bool{$date=DateTimeImmutable::createFromFormat('!Y-m-d',$value);return$date!==false&&$date->format('Y-m-d')===$value;};
$redirectPath=static fn(int$id,string$period):string=>'/multibagger-company.php?id='.$id.($period===''?'':'&period='.rawurlencode($period));
$postList=static function(string$key):array{$values=$_POST[$key]??[];if(!is_array($values))return[];return array_values(array_filter($values,'is_string'));};

if(Request::isPost()){
    if(!$app->session->verifyCsrf(Request::postString('csrf_token',false))){http_response_code(400);exit('Invalid request token.');}
    $action=Request::postString('action');$period=Request::postString('period_end');
    try{
        if(!$validDate($period))throw new InvalidArgumentException('Choose a valid reporting period end date.');
        $methodology=$app->multibagger->activeMethodology();if($methodology===null)throw new InvalidArgumentException('Activate the reviewed multibagger methodology first.');
        if($action==='save_factor'){
            $factorKey=Request::postString('factor_key');$grade=(int)Request::postString('grade');$note=Request::postString('evidence_note');$sourceUrl=Request::postString('evidence_source_url');$documentText=Request::postString('source_document_id');$documentId=$documentText===''?null:(int)$documentText;$governmentText=Request::postString('government_tailwind_review_id');$governmentReviewId=$governmentText===''?null:(int)$governmentText;
            if(!in_array($factorKey,$methodology->factorKeys(),true)||$grade<1||$grade>10)throw new InvalidArgumentException('Choose a valid factor and grade from 1 to 10.');
            if(mb_strlen($note)<3||mb_strlen($note)>1000)throw new InvalidArgumentException('Evidence note must contain 3 to 1,000 characters.');
            if($documentId!==null&&($documentId<1||!$app->multibagger->documentBelongsToCompany($documentId,$companyId)))throw new InvalidArgumentException('The selected PDF does not belong to this company.');
            if($factorKey==='macro_tailwind'){$governmentEvidence=$governmentReviewId===null?null:$app->government->approvedTailwind($governmentReviewId);if($governmentEvidence===null)throw new InvalidArgumentException('Choose a current, human-approved government tailwind review for the macro factor.');$sourceUrl=(string)$governmentEvidence['official_url'];$documentId=null;}
            if($factorKey!=='macro_tailwind'&&$sourceUrl===''&&$documentId===null)throw new InvalidArgumentException('Link an official source URL or a stored filing PDF.');
            if($factorKey!=='macro_tailwind'&&$sourceUrl!==''&&!ResearchEvidenceUrl::isAllowed($sourceUrl))throw new InvalidArgumentException('Evidence URL must use an allowed official exchange, regulator, or government HTTPS host.');
            if($factorKey!=='macro_tailwind')$governmentReviewId=null;
            $app->multibagger->saveFactorReview($companyId,$period,$factorKey,$grade,$note,$sourceUrl===''?null:$sourceUrl,$documentId,$governmentReviewId,$user->id);$app->logger->info('Multibagger factor reviewed.',['company_id'=>$companyId,'period_end'=>$period,'factor_key'=>$factorKey,'grade'=>$grade,'government_review_id'=>$governmentReviewId,'user_id'=>$user->id]);$app->session->flash('success','Factor review saved as a new audit record.');
        }elseif($action==='save_valuation'){
            $decimalFields=['eps','book_value_per_share','dcf_value_per_share','current_price'];$values=[];foreach($decimalFields as$field){$value=Request::postString($field);if(preg_match('/^(?:0|[1-9]\d{0,17})(?:\.\d{1,6})?$/D',$value)!==1||$value==='0')throw new InvalidArgumentException('Every valuation number must be a positive decimal.');$values[$field]=$value;}
            $currency=strtoupper(Request::postString('currency'));$assumptions=Request::postString('dcf_assumptions_note');$note=Request::postString('valuation_evidence_note');$sourceUrl=Request::postString('valuation_evidence_source_url');$documentText=Request::postString('valuation_document_id');$documentId=$documentText===''?null:(int)$documentText;
            if(preg_match('/^[A-Z]{3}$/D',$currency)!==1||mb_strlen($assumptions)<10||mb_strlen($assumptions)>1000||mb_strlen($note)<3||mb_strlen($note)>1000)throw new InvalidArgumentException('Currency, DCF assumptions, or valuation evidence is incomplete.');
            if(!ResearchEvidenceUrl::isAllowed($sourceUrl))throw new InvalidArgumentException('Valuation evidence URL must use an allowed official HTTPS host.');
            if($documentId!==null&&!$app->multibagger->documentBelongsToCompany($documentId,$companyId))throw new InvalidArgumentException('The selected valuation PDF does not belong to this company.');
            $values+=['currency'=>$currency,'dcf_assumptions_note'=>$assumptions,'evidence_note'=>$note,'evidence_source_url'=>$sourceUrl,'source_document_id'=>$documentId];$app->multibagger->saveValuationReview($companyId,$period,$values,$user->id);$app->logger->info('Multibagger valuation reviewed.',['company_id'=>$companyId,'period_end'=>$period,'user_id'=>$user->id]);$app->session->flash('success','Graham/DCF valuation evidence saved.');
        }elseif($action==='save_risk'){
            $marketCap=Request::postString('market_cap_crore');$note=Request::postString('risk_evidence_note');$sourceUrl=Request::postString('risk_evidence_source_url');if(preg_match('/^(?:0|[1-9]\d{0,17})(?:\.\d{1,6})?$/D',$marketCap)!==1||$marketCap==='0')throw new InvalidArgumentException('Market capitalization must be a positive crore value.');if(mb_strlen($note)<3||mb_strlen($note)>1000||!ResearchEvidenceUrl::isAllowed($sourceUrl))throw new InvalidArgumentException('Risk evidence note or official source URL is invalid.');
            $riskConfig=$methodology->definition['microcap_adjustments'];$allowedRed=array_column($riskConfig['red_flags'],'key');$allowedGreen=array_column($riskConfig['green_flags'],'key');$red=array_values(array_intersect($postList('red_flags'),$allowedRed));$green=array_values(array_intersect($postList('green_flags'),$allowedGreen));$app->multibagger->saveRiskReview($companyId,$period,$marketCap,$red,$green,$note,$sourceUrl,$user->id);$app->logger->info('Multibagger risk review saved.',['company_id'=>$companyId,'period_end'=>$period,'red_flag_count'=>count($red),'green_flag_count'=>count($green),'user_id'=>$user->id]);$app->session->flash('success','Market-cap and microcap risk review saved.');
        }elseif($action==='run_score'){
            $shariaPass=$app->multibagger->currentShariaPass($companyId,$period);if($shariaPass===null)throw new InvalidArgumentException('A same-period pass under the active Sharia policy is required before scoring.');$result=(new MultibaggerScoringEngine(new DecimalMath()))->score($methodology,$shariaPass,$app->multibagger->factorReviews($companyId,$period),$app->multibagger->valuationReview($companyId,$period),$app->multibagger->riskReview($companyId,$period));$scoreId=$app->multibagger->recordScore($companyId,$methodology,(int)$shariaPass['id'],$period,$result,$user->id);$app->logger->info('Multibagger score recorded.',['score_id'=>$scoreId,'company_id'=>$companyId,'status'=>$result->status,'final_score'=>$result->finalScore,'alert_eligible'=>$result->alertEligible,'user_id'=>$user->id]);$app->session->flash($result->status==='scored'?'success':'warning',$result->status==='scored'?'Score '.$result->finalScore.' / 10 recorded.':'Evidence remains insufficient; no score was assigned.');
        }else throw new InvalidArgumentException('Invalid multibagger review action.');
    }catch(InvalidArgumentException$exception){$app->session->flash('error',$exception->getMessage());}catch(Throwable$exception){$app->logger->error('Multibagger action failed.',['company_id'=>$companyId,'action'=>$action,'exception_class'=>$exception::class,'user_id'=>$user->id]);$app->session->flash('error','The action could not be completed. Run the health check and inspect the private application log.');}
    $app->session->rotateCsrfToken();Response::redirect($redirectPath($companyId,$period));
}

$methodology=$app->multibagger->activeMethodology();$selectedPeriod=Request::queryString('period');if(!$validDate($selectedPeriod))$selectedPeriod=(new DateTimeImmutable('now'))->format('Y-m-d');$shariaPass=$app->multibagger->currentShariaPass($companyId,$selectedPeriod);$factors=$app->multibagger->factorReviews($companyId,$selectedPeriod);$valuation=$app->multibagger->valuationReview($companyId,$selectedPeriod);$risk=$app->multibagger->riskReview($companyId,$selectedPeriod);$documents=$app->multibagger->documentsForCompany($companyId);$governmentTailwinds=$app->government->approvedTailwinds();$history=$app->multibagger->scoreHistory($companyId);
Page::begin((string)$company['symbol'].' potential review',(string)$config->get('app.name','HalalPulse'),$user,'multibagger',$app->session->csrfToken());
?>
<div class="page-heading"><div><p class="eyebrow"><?=Page::escape($company['exchange'])?> · <?=Page::escape($company['symbol'])?></p><h1><?=Page::escape($company['company_name'])?></h1><p class="muted">Factor-level evidence, conservative dual valuation, microcap risks, and immutable score history.</p></div><a class="button button-secondary" href="/multibagger.php">Back to queue</a></div>
<?php Page::flash($app->session->consumeFlash()); ?>
<section class="policy-banner"><div><p class="eyebrow">Reporting period</p><form class="period-picker" method="get"><input type="hidden" name="id" value="<?=Page::escape($companyId)?>"><input name="period" type="date" value="<?=Page::escape($selectedPeriod)?>"><button class="button button-secondary button-small">Load</button></form></div><div class="policy-meta"><?php if($shariaPass!==null):?><span class="status status-passed">Current Sharia pass</span><?php else:?><span class="status status-insufficient">No same-period Sharia pass</span><?php endif;?><?php if($methodology!==null):?><span class="mono"><?=Page::escape($methodology->version)?> · <?=Page::escape(count($factors))?>/<?=Page::escape(count($methodology->factors()))?> factors</span><?php endif;?></div></section>
<?php if($methodology===null):?><section class="notice-card notice-error"><strong>Methodology gate closed</strong><p>Activate the reviewed local methodology before entering or calculating scores.</p></section><?php else:?>
<section class="review-grid">
<article class="panel"><div class="panel-heading"><div><p class="eyebrow">100% weighted scorecard</p><h2>Factor review</h2></div><span class="status"><?=Page::escape(count($factors))?> / <?=Page::escape(count($methodology->factors()))?></span></div><form class="stacked-form form-section" method="post"><input type="hidden" name="csrf_token" value="<?=Page::escape($app->session->csrfToken())?>"><input type="hidden" name="company_id" value="<?=Page::escape($companyId)?>"><input type="hidden" name="period_end" value="<?=Page::escape($selectedPeriod)?>"><input type="hidden" name="action" value="save_factor"><label for="factor_key">Factor</label><select id="factor_key" name="factor_key"><?php foreach($methodology->factors() as$factor):?><option value="<?=Page::escape($factor['key'])?>"><?=Page::escape($factor['label'])?> · <?=Page::escape($factor['weight_percent'])?>%</option><?php endforeach;?></select><label for="grade">Grade (1 strongest, 10 weakest)</label><select id="grade" name="grade"><?php for($grade=1;$grade<=10;$grade++):?><option value="<?=$grade?>"><?=$grade?></option><?php endfor;?></select><label for="evidence_note">Evidence and calculation note</label><textarea id="evidence_note" name="evidence_note" maxlength="1000" required></textarea><label for="evidence_source_url">Official source URL (non-macro factors)</label><input id="evidence_source_url" name="evidence_source_url" type="url"><label for="source_document_id">Stored filing PDF (non-macro factors)</label><select id="source_document_id" name="source_document_id"><option value="">No linked PDF</option><?php foreach($documents as$document):?><option value="<?=Page::escape($document['id'])?>">#<?=Page::escape($document['id'])?> · <?=Page::escape($document['announced_at'])?> · <?=Page::escape($document['subject'])?></option><?php endforeach;?></select><label for="government_tailwind_review_id">Approved government evidence (required for macro tailwind)</label><select id="government_tailwind_review_id" name="government_tailwind_review_id"><option value="">No government review selected</option><?php foreach($governmentTailwinds as$tailwind):?><option value="<?=Page::escape($tailwind['id'])?>"><?=Page::escape($tailwind['source'])?> · <?=Page::escape($tailwind['sector'])?> · <?=Page::escape($tailwind['published_at'])?> · <?=Page::escape($tailwind['title'])?></option><?php endforeach;?></select><small>Approve evidence first in <a href="/government.php?status=pending">Tailwinds</a>. The official URL is copied from the reviewed record and cannot be typed manually for this factor.</small><button class="button button-primary">Save factor review</button></form></article>
<article class="panel"><div class="panel-heading"><div><p class="eyebrow">Dual-method gate</p><h2>Valuation evidence</h2></div><?php if($valuation!==null):?><span class="status status-passed">Reviewed</span><?php endif;?></div><form class="stacked-form form-section" method="post"><input type="hidden" name="csrf_token" value="<?=Page::escape($app->session->csrfToken())?>"><input type="hidden" name="company_id" value="<?=Page::escape($companyId)?>"><input type="hidden" name="period_end" value="<?=Page::escape($selectedPeriod)?>"><input type="hidden" name="action" value="save_valuation"><div class="form-row"><div><label for="eps">EPS</label><input id="eps" name="eps" value="<?=Page::escape($valuation['eps']??'')?>" required></div><div><label for="book_value_per_share">Book value/share</label><input id="book_value_per_share" name="book_value_per_share" value="<?=Page::escape($valuation['book_value_per_share']??'')?>" required></div><div><label for="currency">Currency</label><input id="currency" name="currency" value="<?=Page::escape($valuation['currency']??'INR')?>" maxlength="3" required></div></div><div class="form-row"><div><label for="dcf_value_per_share">DCF value/share</label><input id="dcf_value_per_share" name="dcf_value_per_share" value="<?=Page::escape($valuation['dcf_value_per_share']??'')?>" required></div><div><label for="current_price">Current price</label><input id="current_price" name="current_price" value="<?=Page::escape($valuation['current_price']??'')?>" required></div></div><label for="dcf_assumptions_note">DCF assumptions</label><textarea id="dcf_assumptions_note" name="dcf_assumptions_note" maxlength="1000" required><?=Page::escape($valuation['dcf_assumptions_note']??'')?></textarea><label for="valuation_evidence_note">Valuation evidence note</label><textarea id="valuation_evidence_note" name="valuation_evidence_note" maxlength="1000" required><?=Page::escape($valuation['evidence_note']??'')?></textarea><label for="valuation_evidence_source_url">Official price/evidence URL</label><input id="valuation_evidence_source_url" name="valuation_evidence_source_url" type="url" value="<?=Page::escape($valuation['evidence_source_url']??'')?>" required><label for="valuation_document_id">Financial statement PDF (optional)</label><select id="valuation_document_id" name="valuation_document_id"><option value="">No linked PDF</option><?php foreach($documents as$document):?><option value="<?=Page::escape($document['id'])?>" <?=((int)($valuation['source_document_id']??0)===(int)$document['id'])?'selected':''?>>#<?=Page::escape($document['id'])?> · <?=Page::escape($document['subject'])?></option><?php endforeach;?></select><button class="button button-primary">Save valuation review</button></form></article>
</section>
<section class="panel panel-results"><div class="panel-heading"><div><p class="eyebrow">Microcap-aware</p><h2>Market cap and risk flags</h2></div><?php if($risk!==null):?><span class="status status-passed">Reviewed</span><?php endif;?></div><form class="stacked-form" method="post"><input type="hidden" name="csrf_token" value="<?=Page::escape($app->session->csrfToken())?>"><input type="hidden" name="company_id" value="<?=Page::escape($companyId)?>"><input type="hidden" name="period_end" value="<?=Page::escape($selectedPeriod)?>"><input type="hidden" name="action" value="save_risk"><div class="form-row"><div><label for="market_cap_crore">Market cap (₹ crore)</label><input id="market_cap_crore" name="market_cap_crore" value="<?=Page::escape($risk['market_cap_crore']??'')?>" required></div><div><label for="risk_evidence_source_url">Official source URL</label><input id="risk_evidence_source_url" name="risk_evidence_source_url" type="url" value="<?=Page::escape($risk['evidence_source_url']??'')?>" required></div></div><div class="flag-grid"><fieldset><legend>Red flags (+<?=Page::escape($methodology->definition['microcap_adjustments']['red_flag_points'])?> each below ₹<?=Page::escape($methodology->definition['microcap_adjustments']['applies_below_crore'])?> crore)</legend><?php $selectedRed=json_decode((string)($risk['red_flags']??'[]'),true);$selectedRed=is_array($selectedRed)?$selectedRed:[];foreach($methodology->definition['microcap_adjustments']['red_flags'] as$flag):?><label class="check-row"><input type="checkbox" name="red_flags[]" value="<?=Page::escape($flag['key'])?>" <?=in_array($flag['key'],$selectedRed,true)?'checked':''?>> <span><?=Page::escape($flag['label'])?></span></label><?php endforeach;?></fieldset><fieldset><legend>Green flags (−<?=Page::escape($methodology->definition['microcap_adjustments']['green_flag_points'])?> each below ₹<?=Page::escape($methodology->definition['microcap_adjustments']['applies_below_crore'])?> crore)</legend><?php $selectedGreen=json_decode((string)($risk['green_flags']??'[]'),true);$selectedGreen=is_array($selectedGreen)?$selectedGreen:[];foreach($methodology->definition['microcap_adjustments']['green_flags'] as$flag):?><label class="check-row"><input type="checkbox" name="green_flags[]" value="<?=Page::escape($flag['key'])?>" <?=in_array($flag['key'],$selectedGreen,true)?'checked':''?>> <span><?=Page::escape($flag['label'])?></span></label><?php endforeach;?></fieldset></div><label for="risk_evidence_note">Risk review evidence</label><textarea id="risk_evidence_note" name="risk_evidence_note" maxlength="1000" required><?=Page::escape($risk['evidence_note']??'')?></textarea><button class="button button-primary">Save risk review</button></form></section>
<section class="panel panel-results"><div class="panel-heading"><div><p class="eyebrow">Current factor set</p><h2>Reviewed factors</h2></div><span class="status"><?=Page::escape(count($factors))?> / <?=Page::escape(count($methodology->factors()))?></span></div><div class="factor-grid"><?php foreach($methodology->factors() as$factor):$review=$factors[$factor['key']]??null;?><article class="factor-card"><div><strong><?=Page::escape($factor['label'])?></strong><small><?=Page::escape($factor['weight_percent'])?>% weight</small></div><?php if($review===null):?><span class="status status-insufficient">Missing</span><?php else:?><span class="score-pill"><?=Page::escape($review['grade'])?></span><p><?=Page::escape($review['evidence_note'])?><?php if($factor['key']==='macro_tailwind'):?><small><?=Page::escape($review['government_source']??'No current source')?> · <?=Page::escape($review['government_review_sector']??'review required')?> · <?=Page::escape($review['government_review_status']??'invalid')?></small><?php endif;?></p><?php endif;?></article><?php endforeach;?></div><form class="screening-action" method="post"><input type="hidden" name="csrf_token" value="<?=Page::escape($app->session->csrfToken())?>"><input type="hidden" name="company_id" value="<?=Page::escape($companyId)?>"><input type="hidden" name="period_end" value="<?=Page::escape($selectedPeriod)?>"><input type="hidden" name="action" value="run_score"><p>Requires all factors, current approved macro evidence, valuation, risk review, and a same-period pass under the active Sharia policy.</p><button class="button button-primary">Calculate immutable score</button></form></section>
<?php endif;?>
<section class="panel panel-results"><div class="panel-heading"><div><p class="eyebrow">Audit trail</p><h2>Score history</h2></div><span class="status"><?=Page::escape(count($history))?> records</span></div><?php if($history===[]):?><div class="empty-state compact"><p>No scores recorded yet.</p></div><?php else:?><div class="table-wrap"><table><thead><tr><th>Score</th><th>Period</th><th>Methodology</th><th>Valuation</th><th>Alert gate</th><th>Recorded</th></tr></thead><tbody><?php foreach($history as$score):?><tr><td><?=Page::escape($score['final_score']===null?'Insufficient':$score['final_score'].' / 10')?><small><?=Page::escape($score['market_cap_category'])?></small></td><td><?=Page::escape($score['period_end'])?></td><td><?=Page::escape($score['methodology_version'])?></td><td><?=((int)$score['undervalued_by_both']===1)?'<span class="status status-passed">Both agree</span>':'No dual agreement'?></td><td><?=((int)$score['alert_eligible']===1)?'<span class="status status-passed">Eligible</span>':'—'?></td><td><?=Page::escape($score['computed_by_name'])?><small><?=Page::escape($score['computed_at'])?></small></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
<section class="notice-card"><strong>Personal research only</strong><p>SEBI investor education notes that stock-market returns are not guaranteed. Treat this score as a review queue, not advice, and consider your objectives and risk appetite.</p></section>
<?php Page::end(); ?>
